<a href="https://colab.research.google.com/github/AnnaLesyk/numerical-methods-of-programming/blob/main/Lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторна робота №4
Виконала студентка ФІТ 3-14
Лесик Анна

In [ ]:
import numpy as np
# 1)

a = np.array([[2,3,1],[-1,1,0],[1,2,-1]])
print ("matrix a:")
print ( a)
b = np.array([[1,2,1],[0,1,2],[3,1,1]])
print ("matrix b:")
print ( b)

ab = a.dot(b)
print("matrix ab", ab)

ba = b.dot(a)
print("matrix ba", ba)

c = ab - ba
print ("matrix c :")
print ( c)

matrix a:
[[ 2  3  1]
 [-1  1  0]
 [ 1  2 -1]]
matrix b:
[[1 2 1]
 [0 1 2]
 [3 1 1]]
matrix ab [[ 5  8  9]
 [-1 -1  1]
 [-2  3  4]]
matrix ba [[ 1  7  0]
 [ 1  5 -2]
 [ 6 12  2]]
matrix c :
[[ 4  1  9]
 [-2 -6  3]
 [-8 -9  2]]


In [ ]:
import numpy as np
# 2) x *x

x = np.array([[-1,0,2],[0,1,0],[1,2,-1]])
x_2 = x.dot(x)
print ("array x:", x)
print ("array x_2:", x_2)

array x: [[-1  0  2]
 [ 0  1  0]
 [ 1  2 -1]]
array x_2: [[ 3  4 -4]
 [ 0  1  0]
 [-2  0  3]]


In [ ]:
import numpy as np
# 3) c = a * b
a = np.array([[3,0,7],[-4,2,3],[-1,1,2]])
print ("matrix a:")
print ( a)
b = np.array([[1],[2],[4]])
print ("matrix b:")
print ( b)

ab = a.dot(b)
print("matrix ab")
print (ab)



matrix a:
[[ 3  0  7]
 [-4  2  3]
 [-1  1  2]]
matrix b:
[[1]
 [2]
 [4]]
matrix ab
[[31]
 [12]
 [ 9]]


In [ ]:
import numpy as np
#4)
a = np.array([[1,2,3,4],[-1,2,1],[1,3,2]])
print ("matrix a:")
print ( a)
a_det = np.linalg.det(a)
print (a_det)



matrix a:
[[ 1  2  3]
 [-1  2  1]
 [ 1  3  2]]
-7.999999999999998


In [ ]:
#5)
import numpy as np
b = np.matrix([[1,2,3,4,],[-2,1,-4,3],[3,-4,-1,2],[4,3,-2,-1]])
print ("matrix b:")
print (b)
b_det = np.linalg.det(b)
print (b_det)



matrix b:
[[ 1  2  3  4]
 [-2  1 -4  3]
 [ 3 -4 -1  2]
 [ 4  3 -2 -1]]
900.0000000000009


In [ ]:
# 6)
import numpy as np
b = np.matrix([[1,1,1,1],[1,1,-1,-1],[1,-1,1,-1],[1,-1,-1,1]])
print ("matrix b:")
print (b)
b_inv = np.linalg.inv(b)
print("inversed ")
print (b_inv)

matrix b:
[[ 1  1  1  1]
 [ 1  1 -1 -1]
 [ 1 -1  1 -1]
 [ 1 -1 -1  1]]
inversed 
[[ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25 -0.25 -0.25]
 [ 0.25 -0.25  0.25 -0.25]
 [ 0.25 -0.25 -0.25  0.25]]


In [ ]:
#7)
import numpy as np
r = np.matrix([[-2,3,1,-1],[3,2,1,4],[1,2,3,4],[0,2,3,3]])
print ("matrix r:")
print (r)
rank = np.linalg.matrix_rank(r)
print (rank)


matrix r:
[[-2  3  1 -1]
 [ 3  2  1  4]
 [ 1  2  3  4]
 [ 0  2  3  3]]
3


In [ ]:
#8)матричний метод
import numpy as np
a = np.matrix([[1,1,-1,],[3,-1,2],[4,4,-3]])
b = np.matrix([[-2],[9],[-5]])
print ("matrix A:")
print (a)
print ("matrix B:")
print (b)
a_inv = np.linalg.inv(a)
print ("matrix A_inv:")
print (a_inv)
x = a_inv.dot(b)
print ("x:")
print (x)

matrix A:
[[ 1  1 -1]
 [ 3 -1  2]
 [ 4  4 -3]]
matrix B:
[[-2]
 [ 9]
 [-5]]
matrix A_inv:
[[ 1.25  0.25 -0.25]
 [-4.25 -0.25  1.25]
 [-4.   -0.    1.  ]]
x:
[[1.]
 [0.]
 [3.]]


In [ ]:
import numpy as np
# 8)метод Крамера
a = np.matrix([[1,1,-1,],[3,-1,2],[4,4,-3]])
b = np.matrix([[-2],[9],[-5]])
def kram(a,b):
    det_a = np.linalg.det(a)
    if det_a != 0:
       a1 = np.matrix(a)
       a2 = np.matrix(a)
       a3 = np.matrix(a)
       a1[:, 0] = b
       a2[:, 1] = b
       a3[:, 2] = b
       x = np.linalg.det(a1)/det_a
       y =np.linalg.det(a2)/det_a
       z= np.linalg.det(a3)/det_a
       print('Solving a system of linear algebraic equations by Cramer*s method')
       print('x=',x.round(3),'y=',y.round(3),'z=',z.round(3))
    else:
        print('Determinant equals zero, the system has no solutions')
    return x,y,z
kram(a,b)
s= np.linalg.solve(a,b).round(3)
print (s)


Solving a system of linear algebraic equations by Cramer*s method
x= 1.0 y= -0.0 z= 3.0
[[ 1.]
 [-0.]
 [ 3.]]


In [ ]:
import numpy as np
import random

m = input('m = ')
n = input('n = ')

m = int(m)
n = int(n)

matrix = [ [random.randint(1, 11) for j in range(n)] for i in range(m) ]
print ('matrix : ')
for i in range(m):
  print (matrix[i])

sum_matrix = sum( matrix[i][j] for i in range(m) for j in range(n))
print ("the sum of all matrix elements =  ", sum_matrix)

m = 2
n = 2
matrix : 
[11, 4]
[5, 5]
the sum of all matrix elements =   25
